### PR TITLE
Golint a little happier

### PR DESCRIPTION
**Pull request by lloydde**

### CODE REVIEW

**Comment by lloydde** [comment]
The tests still all pass. The travis build fails on goveralls, because of #53 .

**Comment by krobertson** [comment]
Will discuss with @derekcollison and internally. A number of the renames may easily break compatibility for consumers of the library, and Go currently lacks a good way to do versioning around these things.

**Comment by lloydde** [comment]
Thanks @krobertson. I'm not passionate about any of these changes. If you do find an example of a breakage, I'd like to add a test case.

**Comment by krobertson** [comment]
I think its more because nats is a library rather than a server... so changing public naming can break consumers. I know merging this right now would break some of our internal repos which are using NATS.

**Comment by lloydde** [comment]
Thanks for the further explaination @krobertson . I'm new to golang. I just researched the current state of  dependency versioning in go, and so will close this pull request. The ship here has sailed.

**Pull request closed without merging**
